/* Core Banking Data Model - Schema Definition */


-- COUNTRY

CREATE TABLE COUNTRY (
    COUNTRY_ID INT PRIMARY KEY,
    COUNTRY_NAME NVARCHAR(30) NOT NULL,
    COUNTRY_TELEPHONE_CODE NVARCHAR(3) DEFAULT '+90',
    COUNTRY_CODE NVARCHAR(5) NOT NULL UNIQUE
);


-- CITY

CREATE TABLE CITY (
    CITY_ID INT PRIMARY KEY,
    COUNTRY_ID INT NOT NULL,
    CITY_TELEPHONE_CODE NVARCHAR(4) NOT NULL,
    CITY_NAME NVARCHAR(30) NOT NULL,
    CONSTRAINT FK_CITY_COUNTRY
        FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID)
);


-- LOCATION

CREATE TABLE LOCATION (
    LOCATION_ID INT IDENTITY(1,1) PRIMARY KEY,
    STREET_NAME NVARCHAR(50),
    CITY_ID INT NOT NULL,
    APARTMENT_NO SMALLINT,
    FLOOR TINYINT,
    ZIP_CODE INT,
    NEIGHBORHOOD_NAME NVARCHAR(50),
    ADDRESS_DESCRIPTION NVARCHAR(100),
    CONSTRAINT FK_LOCATION_CITY
        FOREIGN KEY (CITY_ID) REFERENCES CITY(CITY_ID)
);


-- BRANCH

CREATE TABLE BRANCH (
    BRANCH_ID INT IDENTITY(1,1) PRIMARY KEY,
    BRANCH_CODE TINYINT NOT NULL UNIQUE,
    BRANCH_MANAGER NVARCHAR(50),
    BRANCH_NAME NVARCHAR(50) NOT NULL,
    BRANCH_OPEN_DATE DATE NOT NULL,
    LOCATION_ID INT NOT NULL,
    CONSTRAINT FK_BRANCH_LOCATION
        FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID)
);


-- CREDIT SCORE

CREATE TABLE CREDIT_SCORE (
    CREDIT_SCORE_ID INT PRIMARY KEY,
    SCORE_VALUE SMALLINT,
    RISK_GROUP NVARCHAR(20)
);

-- =========================
-- CUSTOMER
-- =========================
CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_TC NVARCHAR(11) NOT NULL UNIQUE,
    FIRST_NAME NVARCHAR(30) NOT NULL,
    LAST_NAME NVARCHAR(30) NOT NULL,
    EMAIL NVARCHAR(40) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    LOCATION_ID INT NOT NULL,
    JOB_TITLE NVARCHAR(50),
    CREDIT_SCORE_ID INT,
    MONTHLY_INCOME DECIMAL(18,2),

    CONSTRAINT FK_CUSTOMER_LOCATION
        FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID),

    CONSTRAINT FK_CUSTOMER_CREDIT
        FOREIGN KEY (CREDIT_SCORE_ID) REFERENCES CREDIT_SCORE(CREDIT_SCORE_ID)
);

-- =========================
-- EMPLOYEE
-- =========================
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT IDENTITY(1,1) PRIMARY KEY,
    FIRST_NAME NVARCHAR(30) NOT NULL,
    LAST_NAME NVARCHAR(30) NOT NULL,
    LOCATION_ID INT NOT NULL,
    BRANCH_ID INT NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    START_DATE DATE NOT NULL,
    POSITION NVARCHAR(50) NOT NULL,
    SALARY DECIMAL(18,2) NOT NULL,

    CONSTRAINT FK_EMPLOYEE_LOCATION
        FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID),

    CONSTRAINT FK_EMPLOYEE_BRANCH
        FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
);

-- =========================
-- ACCOUNT
-- =========================
CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    IBAN NVARCHAR(34) NOT NULL UNIQUE,
    ACCOUNT_TYPE NVARCHAR(20) NOT NULL,
    ACCOUNT_NUMBER NVARCHAR(20) NOT NULL UNIQUE,
    BRANCH_ID INT NOT NULL,
    OPEN_DATE DATE NOT NULL,

    CONSTRAINT FK_ACCOUNT_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),

    CONSTRAINT FK_ACCOUNT_BRANCH
        FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
);


-- PHONE_CUSTOMER

CREATE TABLE PHONE_CUSTOMER (
    PHONE_ID INT IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    PHONE_NUMBER NVARCHAR(15) NOT NULL,
    PHONE_DESCRIPTION NVARCHAR(30),

    CONSTRAINT UQ_PHONE_NUMBER UNIQUE (PHONE_NUMBER),

    CONSTRAINT FK_PHONE_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);


-- PHONE_EMPLOYEE

CREATE TABLE PHONE_EMPLOYEE (
    PHONE_ID INT IDENTITY(1,1) PRIMARY KEY,
    EMPLOYEE_ID INT NOT NULL,
    PHONE_NUMBER NVARCHAR(15) NOT NULL,
    PHONE_DESCRIPTION NVARCHAR(30),

    CONSTRAINT FK_PHONE_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);


-- CREDIT CARD

CREATE TABLE CREDIT_CARD (
    CARD_ID INT IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    CARD_NUMBER NVARCHAR(30) NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    CARD_LIMIT DECIMAL(18,2) NOT NULL,
    MAX_LIMIT DECIMAL(18,2),
    CVV NVARCHAR(3) NOT NULL,
    CARD_PASSWORD NVARCHAR(10) NOT NULL,

    CONSTRAINT FK_CARD_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);


-- TRANSACTION TYPE

CREATE TABLE TRANSACTION_TYPE (
    TRANSACTION_TYPE_ID INT PRIMARY KEY,
    TYPE_NAME NVARCHAR(30),
    TYPE_DESCRIPTION NVARCHAR(100)
);


-- TRANSACTIONS

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID INT IDENTITY(1,1) PRIMARY KEY,
    FROM_ACCOUNT_ID INT NOT NULL,
    TO_ACCOUNT_ID INT NOT NULL,
    TRANSACTION_TYPE_ID INT NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    AMOUNT DECIMAL(18,2) NOT NULL,

    CONSTRAINT FK_TRANSACTION_FROM_ACCOUNT
        FOREIGN KEY (FROM_ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID),

    CONSTRAINT FK_TRANSACTION_TO_ACCOUNT
        FOREIGN KEY (TO_ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID),

    CONSTRAINT FK_TRANSACTION_TYPE
        FOREIGN KEY (TRANSACTION_TYPE_ID) REFERENCES TRANSACTION_TYPE(TRANSACTION_TYPE_ID)
);
